// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxs2xSLYA_WqSi3FxJjO58FO9b0wEXhM',
    appId: '1:188984025105:web:2878598e4ecd73d53591b0',
    messagingSenderId: '188984025105',
    projectId: 'longtimecare-bda93',
    authDomain: 'longtimecare-bda93.firebaseapp.com',
    storageBucket: 'longtimecare-bda93.appspot.com',
    measurementId: 'G-FJY4NMZ2EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXS3fyr8YYp_Ie3nPbSnrduoQGk9SS66I',
    appId: '1:188984025105:android:5f79591c961bc47b3591b0',
    messagingSenderId: '188984025105',
    projectId: 'longtimecare-bda93',
    storageBucket: 'longtimecare-bda93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbY0pjryR_3yPp_oUhd-e-rzSdKcMhr_s',
    appId: '1:188984025105:ios:0a96fd647358b9f93591b0',
    messagingSenderId: '188984025105',
    projectId: 'longtimecare-bda93',
    storageBucket: 'longtimecare-bda93.appspot.com',
    iosClientId: '188984025105-pdhvsvcpae36roe6j4usrg79qa4cbapt.apps.googleusercontent.com',
    iosBundleId: 'com.hcl.longTimeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbY0pjryR_3yPp_oUhd-e-rzSdKcMhr_s',
    appId: '1:188984025105:ios:d47be59b85a0c0a73591b0',
    messagingSenderId: '188984025105',
    projectId: 'longtimecare-bda93',
    storageBucket: 'longtimecare-bda93.appspot.com',
    iosClientId: '188984025105-8emdn5ekas972ij41bns6kk3jdq10ckq.apps.googleusercontent.com',
    iosBundleId: 'com.hcl.longTimeCare.RunnerTests',
  );
}
